
ITEMS_CONCAT_HYPERPARAMETERS = {
    'window_size': [1,3,5]
}

ITEMS_MEAN_HYPERPARAMETERS = {
    'num_items_for_mean': [0]
}

USER_HYPERPARAMETERS = {

}

ITEMS_CONCAT_USER_HYPERPARAMETERS = {
    **ITEMS_CONCAT_HYPERPARAMETERS,
    **USER_HYPERPARAMETERS
}

ITEMS_MEAN_USER_HYPERPARAMETERS = {
    **ITEMS_MEAN_HYPERPARAMETERS,
    **USER_HYPERPARAMETERS
}

ITEMS_CONCAT_ITEMS_MEAN_HYPERPARAMETERS = {
    **ITEMS_MEAN_HYPERPARAMETERS,
    **ITEMS_CONCAT_HYPERPARAMETERS
}

ITEMS_CONCAT_ITEMS_MEAN_USER_HYPERPARAMETERS = {
    **ITEMS_CONCAT_HYPERPARAMETERS,
    **ITEMS_MEAN_HYPERPARAMETERS,
    **USER_HYPERPARAMETERS
}